#numbers
def numbers():
    one = tkinter.Button(cc, text="1", command=lambda: add("1"))
    one.grid(row=1,column=0)
    two = tkinter.Button(cc, text="2", command=lambda: add("2"))
    two.grid(row=1,column=2)
    three = tkinter.Button(cc, text="3", command=lambda: add("3"))
    three.grid(row=1,column=3)
    four = tkinter.Button(cc, text="4", command=lambda: add("4"))
    four.grid(row=2,column=0)
    five = tkinter.Button(cc, text="5", command=lambda: add("5"))
    five.grid(row=2,column=2)
    six = tkinter.Button(cc, text="6", command=lambda: add("6"))
    six.grid(row=2,column=3)
    seven = tkinter.Button(cc, text="7", command=lambda: add("7"))
    seven.grid(row=3,column=0)
    eight = tkinter.Button(cc, text="8", command=lambda: add("8"))
    eight.grid(row=3,column=2)
    nine = tkinter.Button(cc, text="9", command=lambda: add("9"))
    nine.grid(row=3,column=3)
    zero = tkinter.Button(cc, text="0", command=lambda: add("0"))
    zero.grid(row=4,column=2)